import { NextResponse } from "next/server";
import { siteConfig } from "../../../../site.config";

/**
 * /.well-known/agents.json — AI Agent Tool Discovery
 *
 * Machine-readable service description for AI agents.
 * Spec: https://github.com/nicepkg/agents.json
 *
 * Generated by Design Template (StudioMeyer)
 */
export function GET() {
  const siteUrl = siteConfig.company.url;

  const agentsJson = {
    schema_version: "1.0",
    name: siteConfig.company.name,
    description: `${siteConfig.company.name} — ${siteConfig.company.tagline}. AI-Ready with WebMCP support.`,
    url: siteUrl,
    logo: `${siteUrl}/icon.svg`,
    contact: {
      email: siteConfig.contact.email,
      url: `${siteUrl}/de#contact`,
    },
    tools: [
      {
        name: "submit_contact",
        description: "Send a contact inquiry. Returns confirmation.",
        endpoint: "/api/v1/contact",
        method: "POST",
        parameters: {
          name: { type: "string", description: "Full name", required: true },
          email: { type: "string", description: "Email address", required: true },
          message: { type: "string", description: "Message content", required: true },
        },
      },
      {
        name: "get_company_info",
        description: "Get company information: address, contact details, platform overview.",
        endpoint: "/api/v1/company",
        method: "GET",
        parameters: {},
      },
      {
        name: "request_demo",
        description: "Request a product demo or consultation for the SaaS platform.",
        endpoint: "/api/v1/contact",
        method: "POST",
        parameters: {
          name: { type: "string", description: "Full name", required: true },
          email: { type: "string", description: "Business email address", required: true },
          message: { type: "string", description: "Company name, team size, and use case", required: true },
        },
      },
      {
        name: "get_pricing",
        description: "Get pricing tiers and plan details for the SaaS platform.",
        endpoint: "/api/v1/company",
        method: "GET",
        parameters: {},
      },
    ],
    capabilities: {
      webmcp: true,
      a2a: false,
      languages: ["de", "en", "es"],
    },
    provider: {
      name: siteConfig.company.name,
      url: siteConfig.company.url,
    },
  };

  return NextResponse.json(agentsJson, {
    headers: {
      "Cache-Control": "public, max-age=86400, stale-while-revalidate=604800",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET",
    },
  });
}
