import { NextResponse } from "next/server";
import { siteConfig } from "../../../../site.config";

/**
 * /.well-known/agent-card.json — A2A Agent Discovery
 *
 * Agent Card for the A2A protocol (Agent-to-Agent).
 * Spec: https://google.github.io/A2A/
 *
 * Generated by SaaS Landing Template (Aklow Labs)
 */
export function GET() {
  const siteUrl = siteConfig.company.url;

  const agentCard = {
    name: siteConfig.company.name,
    description: `${siteConfig.company.name} — ${siteConfig.company.description}`,
    url: siteUrl,
    version: "1.0.0",
    capabilities: {
      streaming: false,
      pushNotifications: false,
      stateTransitionHistory: false,
    },
    defaultInputModes: ["text"],
    defaultOutputModes: ["text"],
    skills: [
      {
        id: "contact",
        name: "Contact Form",
        description: `Submit a contact inquiry to ${siteConfig.company.name}.`,
        tags: ["contact", "inquiry", "message"],
        examples: [
          `I want to get in touch with ${siteConfig.company.name}`,
          "Send a message to the sales team",
        ],
      },
      {
        id: "info",
        name: "Company Information",
        description: `Get business details and contact information for ${siteConfig.company.name}.`,
        tags: ["info", "location", "about"],
        examples: [
          `What does ${siteConfig.company.name} offer?`,
          "Tell me about the platform",
        ],
      },
      {
        id: "demo",
        name: "Request Demo",
        description: "Request a product demo or consultation for the SaaS platform.",
        tags: ["demo", "trial", "consultation", "sales"],
        examples: [
          "I want to request a demo",
          "Can I try the platform before buying?",
        ],
      },
      {
        id: "pricing",
        name: "Pricing Information",
        description: "Get pricing tiers and plan details.",
        tags: ["pricing", "plans", "cost", "subscription"],
        examples: [
          "What are your pricing plans?",
          "How much does the platform cost?",
        ],
      },
    ],
    provider: {
      organization: "Aklow Labs",
      url: "https://aklow-labs.com",
    },
  };

  return NextResponse.json(agentCard, {
    headers: {
      "Cache-Control": "public, max-age=86400, stale-while-revalidate=604800",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET",
    },
  });
}
