import { siteConfig } from "../../site.config";

/**
 * /llms.txt — LLM-readable index
 *
 * Plain text overview of the business for AI systems.
 * Spec: https://llmstxt.org
 *
 * Generated by SaaS Landing Template (Aklow Labs)
 */
export async function GET() {
  const siteUrl = siteConfig.company.url;

  const content = `# ${siteConfig.company.name}

> ${siteConfig.company.tagline} — ${siteConfig.company.description}

${siteConfig.company.name} is an all-in-one business automation platform. Automate workflows, scale operations, and grow your business with intelligent tools.

## Contact
- Phone: ${siteConfig.contact.phone}
- Email: ${siteConfig.contact.email}
- Address: ${siteConfig.address.street}, ${siteConfig.address.zip} ${siteConfig.address.city}, ${siteConfig.address.country}
- Website: ${siteUrl}

## Business Hours
- ${siteConfig.hours.openingHours}

## Platform Features
- Workflow automation
- Team collaboration
- Analytics and reporting
- API integrations
- Multi-language support (DE/EN/ES)

## Pricing
- Starter, Professional, and Enterprise tiers available
- Custom plans for large teams
- Free trial available

## Features
- Modern SaaS architecture
- Enterprise-grade security
- 99.9% uptime SLA
- AI-Ready with agents.json support

## API for AI Agents
- [Contact Form](${siteUrl}/api/v1/contact) — POST with name, email, message
- [Company Info](${siteUrl}/api/v1/company) — GET
- [Agent Discovery](${siteUrl}/.well-known/agents.json)
- [A2A Agent Card](${siteUrl}/.well-known/agent-card.json)

## Legal
- [Imprint](${siteUrl}/de/impressum)
- [Privacy](${siteUrl}/de/datenschutz)

---
Template by [Aklow Labs](https://aklow-labs.com)
`;

  return new Response(content, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=86400, stale-while-revalidate=604800",
    },
  });
}
